DiscLifts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^site/', include('footer.urls', namespace='footer')),
    url(r'^user/', include('userprofile.urls', namespace='user')),
    url(r'^', include('posts.urls', namespace='posts')),
]

postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import OPTIONS
from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView)


urlpatterns = [
    url(r'^inbox/(?:(?P<option>'+OPTIONS+')/)?$', InboxView.as_view(), name='inbox'),
    url(r'^sent/(?:(?P<option>'+OPTIONS+')/)?$', SentView.as_view(), name='sent'),
    url(r'^archives/(?:(?P<option>'+OPTIONS+')/)?$', ArchivesView.as_view(), name='archives'),
    url(r'^trash/(?:(?P<option>'+OPTIONS+')/)?$', TrashView.as_view(), name='trash'),
    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$', WriteView.as_view(), name='write'),
    url(r'^reply/(?P<message_id>[\d]+)/$', ReplyView.as_view(), name='reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', MessageView.as_view(), name='view'),
    url(r'^view/t/(?P<thread_id>[\d]+)/$', ConversationView.as_view(), name='view_conversation'),
    url(r'^archive/$', ArchiveView.as_view(), name='archive'),
    url(r'^delete/$', DeleteView.as_view(), name='delete'),
    url(r'^undelete/$', UndeleteView.as_view(), name='undelete'),
    url(r'^$', RedirectView.as_view(url='inbox/', permanent=True)),
]

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^events/$', views.events, name='events'),
    url(r'^past_events/$', views.past_events, name='past_events'),
    url(r'^events/(?P<id>\d+)/$', views.event_posts, name='event_posts'),
    url(r'^events/posts/(?P<id>\d+)/$', views.posts, name='posts'),
    url(r'^add_post/(?P<event_id>\d+)/$', views.add_post, name='add_post'),
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^add_event/$', views.add_event, name='add_event'),
    url(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    url(r'^delete_post/(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
    url(r'^delete_event/(?P<event_id>\d+)/$', views.delete_event, name='delete_event'),
    url(r'^events_user/(?P<profile_id>\d+)/$', views.events_user, name='events_user'),
    url(r'^event_info/(?P<event_id>\d+)/$', views.event_info, name='event_info'),
    url(r'^edit_event/(?P<event_id>\d+)/$', views.edit_event, name='edit_event'),
    url(r'^how_it_works/$', views.how_it_works, name='how_it_works'),

]

userprofile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^profile/(?P<profile_id>\d+)/$', views.profile, name='profile'),
    url(r'^update_profile/$', views.update_profile, name='update_profile'),
    url(r'^delete_account/$', views.delete_profile_request, name='delete_profile_request'),

]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.urlresolvers import reverse


class UserProfile(models.Model):
    # class Meta:
    #     app_label = 'userprofile'
    # This links to the user to the user provided by django auth
    user = models.OneToOneField(User, related_name="profile")
    email_notification = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        # userprofile_object.get_absolute_url - userprofile_object (eg UserProfile.objects.get(user_id=request.user.id)
        # that specific user profile object will link to the appropriate url with the kwarg 'profile_id' below relating
        # to <profile_id> in the url.py file
        return reverse('user:profile', kwargs={'profile_id': self.user_id})


# sends a signal every time a new user is created, and calls this method to create the profile
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, new = UserProfile.objects.get_or_create(user=instance)

userprofile/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User



class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        # exclude the user field from the form
        exclude = ('user',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', ]

userprofile/views.py
from __future__ import absolute_import

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail

from .models import UserProfile
from .forms import UserProfileForm, UserForm
from posts.models import Posts


# from ..posts.forms import AddPostForm, AddEventForm

@login_required
def profile(request, profile_id):
    user_django_inst = get_object_or_404(User, id=profile_id)
    user_profile = get_object_or_404(UserProfile, user=profile_id)
    current_user_id = request.user.id
    form = UserProfileForm(initial={'email_notification': user_profile.email_notification})

    user_posts_qs = Posts.objects.all().filter(user_id=current_user_id)
    user_posts_qs_paginator = create_pagination(request, user_posts_qs, 5)

    context = {
        'user_profile': user_profile,
        'current_user_id': current_user_id,
        'user_posts_queryset': user_posts_qs_paginator,
        'user_django_inst': user_django_inst,

    }
    return render(request, 'userprofile/profile.html', context)


@login_required
def update_profile(request):
    user_instance = get_object_or_404(UserProfile, user=request.user)
    user_django_inst = get_object_or_404(User, id=user_instance.user_id)

    if request.method == 'POST':

        user_form = UserForm(request.POST)
        user_profile_form = UserProfileForm(request.POST)

        if user_profile_form.is_valid() and user_form.is_valid():
            # The save(commit=False) part allows us to add data to other fields before the whole form is saved. In this
            # case the user has to be associated with a post which is done automatically with request.user which is
            # assigned to the user field in the model Posts

            email_notification = user_profile_form.cleaned_data['email_notification']
            user_instance.email_notification = email_notification
            user_instance.save()

            user_django_inst.first_name = user_form.cleaned_data['first_name']
            user_django_inst.last_name = user_form.cleaned_data['last_name']
            user_django_inst.save()

            return redirect(user_instance)

    else:
        user_profile_form = UserProfileForm(instance=user_instance)
        user_form = UserForm(instance=user_django_inst)

    context = {
        'user_profile_form': user_profile_form,
        'user_form': user_form,
    }

    return render(request, 'userprofile/update_profile.html', context)


def create_pagination(request, queryset, item_limit):
    paginator = Paginator(queryset, item_limit)

    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)

    return queryset


# Sends an email to the admin requesting the deletion of the users account.
def delete_profile_request(request):
    current_user_id = request.user.id
    user_profile = get_object_or_404(UserProfile, user=current_user_id)
    user_django_inst = get_object_or_404(User, id=current_user_id)

    message = 'Current user id: ' + str(current_user_id) + ' has requested a profile delete'
    send_mail(
                'New profile delete request from DiscLifts.com',
                message,
                user_django_inst.email,
                ['disclifts@gmail.com'],
                fail_silently=False,
            )
    return redirect(user_profile)

userprofile/templates/userprofile/profile.html
{% extends 'disclifts/base.html' %}

{% block title %}Profile ¦{% endblock title %}

{% block content %}
<div class="container container-reduced-top-padding">
    <div class="row">
        <div class="col-sm-8">
            <h2>Profile {{ user_profile.user.username }} id= {{ user_profile.user.id }}</h2>
        </div>
        <div class="col-sm-4 h2">
            {% if current_user_id != user_profile.user.id %}
            <a role="button" class="btn btn-primary" href="{% url 'postman:write' user_profile.user %}">
                Message {{user_profile.user }}
            </a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            {% if current_user_id == user_profile.user.id %}
            {# Current user is viewing their own profile #}
            <div class="panel panel-default" style="border-color: #F35A05">
                <table class="table table-bordered">
                    <tr>
                        <th>First Name:</th>
                        <th>{{ user_django_inst.first_name }}</th>
                    </tr>
                    <tr>
                        <th>Last Name:</th>
                        <th>{{ user_django_inst.last_name }}</th>
                    </tr>
                    <tr>
                        <th>Email:</th>
                        <th>{{ user_django_inst.email }}</th>
                    </tr>
                    <tr>
                        <th>Email notification:</th>
                        <th>{{user_profile.email_notification}}</th>
                    </tr>
                </table>
            </div>
            <div class="list-group profile-links">
                <a class="list-group-item" href="{% url 'user:update_profile' %}">Edit profile settings</a>
                <a class="list-group-item" href="{% url 'account_change_password' %}">Change password</a>
                <a class="list-group-item" role="button" id="btn-delete-account"
                   href="{% url 'user:delete_profile_request' %}"
                   onclick="return confirm('Are you sure you want to delete your account?');">
                    Delete account
                </a>
                <a class="list-group-item" href="{% url 'posts:events_user' user_profile.id %}"> View all events from
                    {{user_django_inst.username}}</a>
            </div>

            {% else %}
            {# Current user is viewing another users profile #}
            <p>Date last signed in: {{ user_django_inst.last_login }} </p>
            <a href="{% url 'posts:events_user' user_profile.id %}"> View all events from
                {{user_django_inst.username}}</a><br>
            {% endif %}


        </div>
    </div>

    <h3>{{ user_django_inst.username }} post history</h3>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Lift Type</th>
                    <th>Location</th>
                    <th>Leaving date</th>
                    <th>Leaving time</th>
                    <th>Fulfilled</th>
                    <th>Spaces</th>
                    <th>Event</th>
                </tr>
                </thead>
                {% for post_inst in user_posts_queryset %}

                <tr class="clickable-row" data-url="{{ post_inst.get_absolute_url }}">
                    <td>{% if post_inst.lift_type == 'I have space' %}
                        <i class="fa fa-car" aria-hidden="true"></i> I have space
                        {% else %}
                        <i class="fa fa-thumbs-up" aria-hidden="true"></i> I need a ride
                        {%endif%}
                    </td>
                    <td>{{ post_inst.location }}</td>
                    <td>{{ post_inst.leaving_date }}</td>
                    <td>{{ post_inst.leaving_time }}</td>
                    <td><input type="checkbox" name="fulfilled" {% if post_inst.fulfilled%} checked {%else%}{%endif%}
                               disabled="true">
                    </td>
                    <td>{{ post_inst.spaces }}</td>
                    <td>{{ post_inst.event }}</td>
                    {% if current_user_id == user_profile.user.id %}
                    <td>
                        <a role="button" class="btn btn-primary" href="{% url 'posts:edit_post' post_inst.id %}">
                            Edit post
                        </a>
                    </td>
                    {% endif%}
                </tr>
                {% endfor %}

            </table>
            <div class="pagination">
            <span class="step-links">
                {% if user_posts_queryset.has_previous %}
                <a href="?page={{ user_posts_queryset.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ user_posts_queryset.number }} of {{ user_posts_queryset.paginator.num_pages }}.
                </span>

                {% if user_posts_queryset.has_next %}
                <a href="?page={{ user_posts_queryset.next_page_number }}">next</a>
                {% endif %}
            </span>
            </div>
        </div>

    </div>

</div> <!--container-->
{% endblock %}

userprofile/templates/userprofile/update_profile.html
{% extends 'disclifts/base.html' %}

{% block title %}Update Profile ¦{% endblock title %}

{% block content %}
<div class="container">
    <h2>{{ request.user }} update your profile</h2>
    <div class="row">
        <div class="col-sm-6">
            <form action="/user/update_profile/" method="POST">
                {% csrf_token %}


                <table class="table">
                    {{ user_form.as_table }}
                    <tbody>
                    <tr>
                        <th><label>Email notification:</label></th>
                        <th>{{ user_profile_form.email_notification }}</th>
                    </tr>
                    </tbody>
                    <!--<label>Email notification:</label>-->
                    <!--{{ user_profile_form.email_notification }} <br>-->
                </table>

                <input type="submit" value="Save">

            </form>
        </div>
    </div>

</div>


{% endblock %}