DiscLifts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^site/', include('footer.urls', namespace='footer')),
    url(r'^user/', include('userprofile.urls', namespace='user')),
    url(r'^', include('posts.urls', namespace='posts')),
]

footer/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^contact/$', views.contact_page, name='contact_page'),
    url(r'^termsandconditions/$', views.tnc, name='tnc'),
    url(r'^privacypolicy/$', views.privacy_policy, name='privacy_policy'),
]

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^events/$', views.events, name='events'),
    url(r'^past_events/$', views.past_events, name='past_events'),
    url(r'^events/(?P<id>\d+)/$', views.event_posts, name='event_posts'),
    url(r'^events/posts/(?P<id>\d+)/$', views.posts, name='posts'),
    url(r'^add_post/(?P<event_id>\d+)/$', views.add_post, name='add_post'),
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^add_event/$', views.add_event, name='add_event'),
    url(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    url(r'^delete_post/(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
    url(r'^delete_event/(?P<event_id>\d+)/$', views.delete_event, name='delete_event'),
    url(r'^events_user/(?P<profile_id>\d+)/$', views.events_user, name='events_user'),
    url(r'^event_info/(?P<event_id>\d+)/$', views.event_info, name='event_info'),
    url(r'^edit_event/(?P<event_id>\d+)/$', views.edit_event, name='edit_event'),
    url(r'^how_it_works/$', views.how_it_works, name='how_it_works'),

]

userprofile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^profile/(?P<profile_id>\d+)/$', views.profile, name='profile'),
    url(r'^update_profile/$', views.update_profile, name='update_profile'),
    url(r'^delete_account/$', views.delete_profile_request, name='delete_profile_request'),

]

templates/disclifts/base.html
{% load staticfiles%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    {% block extrahead %}{% endblock extrahead %}
    {% include 'disclifts/head_css.html' %}


</head>
<body>
{% include 'disclifts/nav_bar.html' %}


<!--<div class="container">-->
    {% block postman_menu %}
    {% endblock postman_menu %}
<div class="container container-reduced-top-padding">
    {% block content %}
    {% endblock %}
</div>

<!--</div>-->

<footer class="footer">
    <div class="container" id="footer-menu">
        <a href="{% url 'footer:tnc' %}">Terms and conditions</a>
        <a href="{% url 'footer:privacy_policy' %}">Privacy policy</a>
        <a href="#">About the site</a>
        <a href="#">Sitemap</a>
        <a href="{% url 'footer:contact_page' %}">Contact</a>
    </div>
</footer>
{% include 'disclifts/js.html' %}
</body>
</html>

templates/disclifts/head_css.html
{% load staticfiles %}

<!--Contains various CSS files for loading from base.html-->

<!--Bootstrap CSS-->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">

<!--&lt;!&ndash; Custom styles for this template &ndash;&gt;-->
<!--<link href="navbar-static-top.css" rel="stylesheet">-->
<link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!--Fontawesome-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<!--Custom css styles to override certain class styles-->
<link href="{% static 'css/custom_styles.css' %}" rel="stylesheet">
<link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">

templates/disclifts/js.html
{% load staticfiles %}

<!--Contains and loads all the js files in base.html-->

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/custom_js.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<!-- Begin Cookie Consent plugin by Silktide - http://silktide.com/cookieconsent -->
<script type="text/javascript">
    window.cookieconsent_options = {"message":"This website uses cookies to ensure you get the best experience on our website","dismiss":"Got it!","learnMore":"More info","link":null,"theme":"dark-floating"};

</script>

<script type="text/javascript"
        src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
<!-- End Cookie Consent plugin -->
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

templates/disclifts/nav_bar.html
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'posts:index' %}">Disc Lifts</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'posts:index' %}">Home</a></li>
                <li><a href="{% url 'posts:events' %}">Events</a></li>
                <!--<li><a href="#contact">Contact</a></li>-->
                <!--<li class="dropdown">-->
                <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>-->
                <!--<ul class="dropdown-menu" role="menu">-->
                <!--<li><a href="#">Action</a></li>-->
                <!--<li><a href="#">Another action</a></li>-->
                <!--<li><a href="#">Something else here</a></li>-->
                <!--<li class="divider"></li>-->
                <!--<li class="dropdown-header">Nav header</li>-->
                <!--<li><a href="#">Separated link</a></li>-->
                <!--<li><a href="#">One more separated link</a></li>-->
                <!--</ul>-->
                <!--</li>-->
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li><a href="{% url 'postman:inbox' %}">{% if postman_unread_count %}<i
                        class="fa fa-envelope red"></i>{%else%}<i
                        class="fa fa-envelope-o "></i>{%endif%}</a></li>
                <li><a href="{% url 'user:profile' request.user.id %}"><i class="fa fa-user"></i></i> {{ request.user }}</a>
                </li>
                <li><a href="{% url 'account_logout' %}">Logout</a></li>
                {% endif %}
            </ul>

            {% if not request.user.is_authenticated %}
            <form id="nav-bar-login" class="navbar-form navbar-right" method="post" action="{% url 'account_login' %}">{% csrf_token %}
                <div class="form-group">
                    <!--The name element has to be the same as the name element as the one used by allauth, as does the password name element-->
                    <input type="text" class="form-control" name="login" placeholder="Username">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-default">Login</button>


            </form>
            {% endif %}

        </div><!--/.nav-collapse -->
    </div>
</nav>

templates/disclifts/nav_bar_template.html
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>