DiscLifts/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^site/', include('footer.urls', namespace='footer')),
    url(r'^user/', include('userprofile.urls', namespace='user')),
    url(r'^', include('posts.urls', namespace='posts')),
]

postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import OPTIONS
from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView)


urlpatterns = [
    url(r'^inbox/(?:(?P<option>'+OPTIONS+')/)?$', InboxView.as_view(), name='inbox'),
    url(r'^sent/(?:(?P<option>'+OPTIONS+')/)?$', SentView.as_view(), name='sent'),
    url(r'^archives/(?:(?P<option>'+OPTIONS+')/)?$', ArchivesView.as_view(), name='archives'),
    url(r'^trash/(?:(?P<option>'+OPTIONS+')/)?$', TrashView.as_view(), name='trash'),
    url(r'^write/(?:(?P<recipients>[^/#]+)/)?$', WriteView.as_view(), name='write'),
    url(r'^reply/(?P<message_id>[\d]+)/$', ReplyView.as_view(), name='reply'),
    url(r'^view/(?P<message_id>[\d]+)/$', MessageView.as_view(), name='view'),
    url(r'^view/t/(?P<thread_id>[\d]+)/$', ConversationView.as_view(), name='view_conversation'),
    url(r'^archive/$', ArchiveView.as_view(), name='archive'),
    url(r'^delete/$', DeleteView.as_view(), name='delete'),
    url(r'^undelete/$', UndeleteView.as_view(), name='undelete'),
    url(r'^$', RedirectView.as_view(url='inbox/', permanent=True)),
]

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^events/$', views.events, name='events'),
    url(r'^past_events/$', views.past_events, name='past_events'),
    url(r'^events/(?P<id>\d+)/$', views.event_posts, name='event_posts'),
    url(r'^events/posts/(?P<id>\d+)/$', views.posts, name='posts'),
    url(r'^add_post/(?P<event_id>\d+)/$', views.add_post, name='add_post'),
    url(r'^add_post/$', views.add_post, name='add_post'),
    url(r'^add_event/$', views.add_event, name='add_event'),
    url(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    url(r'^delete_post/(?P<post_id>\d+)/$', views.delete_post, name='delete_post'),
    url(r'^delete_event/(?P<event_id>\d+)/$', views.delete_event, name='delete_event'),
    url(r'^events_user/(?P<profile_id>\d+)/$', views.events_user, name='events_user'),
    url(r'^event_info/(?P<event_id>\d+)/$', views.event_info, name='event_info'),
    url(r'^edit_event/(?P<event_id>\d+)/$', views.edit_event, name='edit_event'),
    url(r'^how_it_works/$', views.how_it_works, name='how_it_works'),

]

userprofile/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^profile/(?P<profile_id>\d+)/$', views.profile, name='profile'),
    url(r'^update_profile/$', views.update_profile, name='update_profile'),
    url(r'^delete_account/$', views.delete_profile_request, name='delete_profile_request'),

]

posts/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


# Create your models here.
class EventsManager(models.Manager):
    def future_events(self):
        future_events_qs = Events.objects.filter(end_date__gte=datetime.date.today()).order_by('start_date')
        return future_events_qs

    def past_events(self):
        past_events_qs = Events.objects.filter(end_date__lte=datetime.date.today()).order_by('start_date')
        return past_events_qs

class Events(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    location = models.CharField(max_length=120, null=True)
    start_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    end_date = models.DateField(auto_now=False, auto_now_add=False, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = "Events"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:event_posts', kwargs={'id': self.id})
        # return "/posts/events/%s" %(self.id)

    objects = EventsManager()


class Posts(models.Model):
    location = models.CharField(max_length=120)
    # The first element in each choices tuple is the actual value to be set on the model, and the second element is the
    # human-readable name
    lift_type = models.CharField(max_length=120,
                                 choices=(('I have space', 'I have space'), ('I need a ride', 'I need a ride')))
    leaving_time = models.CharField(max_length=120)
    spaces = models.IntegerField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    event = models.ForeignKey(Events, on_delete=models.CASCADE, null=True)
    # Each post is linked to a User
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comments = models.TextField(null=True, blank=True)
    fulfilled = models.BooleanField(default=False)
    leaving_date = models.DateField(auto_now=False, auto_now_add=False)
    return_date = models.DateField(auto_now=False, auto_now_add=False, null=True)

    def __str__(self):
        return self.location

    class Meta:
        verbose_name_plural = "Posts"

    def get_absolute_url(self):
        return reverse('posts:posts', kwargs={'id': self.id})



class EventsManager(models.Manager):
    def future_events(self):
        future_events_qs = Events.objects.filter(end_date__gte=datetime.date.today()).order_by('start_date')
        return future_events_qs

posts/forms.py
from django import forms
from .models import Posts, Events


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['event', 'lift_type', 'spaces', 'location', 'leaving_time', 'leaving_date', 'return_date', 'comments']
        # This is for the date picker popup
        widgets = {
            'leaving_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'return_date': forms.DateInput(attrs={'class': 'datepicker'}),
        }
        labels = {
            'location': ('Location'),
        }
        help_texts = {
            'location': ('Location you are leaving from'),
        }
        # error_messages = {
        #     'name': {
        #         'max_length': _("This writer's name is too long."),
        #     },
        # }

        # When this validation is applied and 12 is picked for spaces the submit button returns a None value instead of a
        # httpresponse object
        # def clean_spaces(self):
        #     spaces = self.cleaned_data.get('spaces')
        #     if spaces not in range(1, 10):
        #         raise forms.ValidationError('Please pick a number between 1 and 10')
        #     return spaces


class AddEventForm(forms.ModelForm):
    class Meta:
        model = Events
        fields = ['title', 'content', 'location', 'start_date', 'end_date']
        widgets = {
            'start_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'end_date': forms.DateInput(attrs={'class': 'datepicker'}),
        }


class EditPostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ['event', 'lift_type', 'spaces', 'location', 'leaving_time', 'leaving_date', 'return_date',
                  'fulfilled', 'comments']
        widgets = {
            # The attrs is a dictionary containing HTML attributes to be set on the rendered widget.
            # https://docs.djangoproject.com/en/1.10/ref/forms/widgets/#django.forms.Widget.attrs
            'leaving_date': forms.DateInput(attrs={'class': 'datepicker'}),
            'return_date': forms.DateInput(attrs={'class': 'datepicker'}),
        }
        labels = {
            'location': ('Location'),
        }
        help_texts = {
            'location': ('Location you are leaving from'),
        }

posts/templates/posts/add_event.html
{% extends 'disclifts/base.html' %}


{% block title %}Add Event ¦{% endblock title %}

{% block content %}
<div class="container container-reduced-top-padding">
    <div class="row">
        <div class="col-xs-8">
            <h2>{{ add_event_text }}</h2>
            <form action="/add_event/" method="post">
                {% csrf_token %}
                <table class="table">
                    {{ add_event_form.as_table }}
                </table>
                <input type="submit" value="Submit"/>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

posts/templates/posts/edit_event.html
{% extends 'disclifts/base.html' %}

{% block title %}Edit Event ¦{% endblock title %}

{% block content %}
<div class="container container-reduced-top-padding">
    <h2> {{ page_title }} <a role="button" class="btn btn-danger" href="{% url 'posts:delete_event' event_inst.id %}"
                             onclick="return confirm('Are you sure you want to delete this event?');">Delete event </a>
    </h2>
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="POST">
                {% csrf_token %}
                <table class="table table-hover">
                    {{ edit_event_form.as_table }}
                </table>
                <input type="submit" value="Save">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

posts/templates/posts/event_info.html
{% extends 'disclifts/base.html' %}

{% block title %}Event Info ¦{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{ event_inst.title }} - <a href="{% url 'posts:event_posts' event_inst.id %}">View posts for this
                event</a>
            </h2>
        </div>

    </div>
    <h4>
        Created by - <a href="{% url 'user:profile' event_inst.user_id %}">{{event_inst.user}}</a>
    </h4>
    <div class="row">
        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr>
                    <th>Event location:</th>
                    <th>{{ event_inst.location }}</th>
                </tr>
                <tr>
                    <th>Start date:</th>
                    <th>{{ event_inst.start_date }}</th>
                </tr>
                <tr>
                    <th>End date:</th>
                    <th>{{ event_inst.end_date }}</th>
                </tr>
            </table>
        </div>
    </div>
    <h4>More info:</h4>
    {{ event_inst.content }}


</div>
{% endblock content %}

posts/templates/posts/event_posts.html
{% extends 'disclifts/base.html' %}

{% block title %}Event Posts ¦{% endblock title %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-sm-8">
            <h2>{{ event_id }}</h2>
            <h4><a href="{% url 'posts:event_info' event_id.id %}">View event info</a></h4>
        </div>
        <div class="col-sm-4 h2 a-btn">
            <a class="btn btn-primary btn-lg" href="{% url 'posts:add_post' event_id.id %}" role="button">Create new
                post</a>
            {% if current_user.id == event_id.user_id %}
            <a class="btn btn-primary btn-lg" href="{% url 'posts:edit_event' event_id.id %}" role="button">Edit
                event</a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Lift Type</th>
                    <th>Location</th>
                    <th>Spaces</th>
                    <th>Leaving date</th>
                    <th>Leaving time</th>
                    <th>Return Date</th>
                    <th>Fulfilled</th>
                </tr>
                </thead>
                {% for inst in posts_queryset %}

                <tr class="clickable-row" data-url="{{ inst.get_absolute_url }}">
                    <td>{% if inst.lift_type == 'I have space' %}
                        <i class="fa fa-car" aria-hidden="true"></i> I have space
                        {% else %}
                        <i class="fa fa-thumbs-up" aria-hidden="true"></i> I need a ride
                        {%endif%}
                    </td>
                    <td>{{ inst.location }}</td>
                    <td>{{ inst.spaces }}</td>
                    <td>{{ inst.leaving_date }}</td>
                    <td>{{ inst.leaving_time }}</td>
                    <td>{{ inst.return_date }}</td>
                    <td><input type="checkbox" name="fulfilled" {% if inst.fulfilled%} checked="" {%else%}{%endif%}
                               disabled="true"></td>
                </tr>
                {% endfor %}

            </table>
            {% if not posts_queryset %}
            <p>Sadly there are no posts here, be the first and get the sharing started.</p>
            <!--event_id is a queryset of Events.objects.get(id=id). The event_id.id gets the id of the event to send in the url to the add_posts view-->
            <p><a class="btn btn-primary btn-lg" href="{% url 'posts:add_post' event_id.id %}" role="button">Create new
                post</a></p>

            {% else %}
            <div class="pagination">
            <span class="step-links">
                {% if posts_queryset.has_previous %}
                <a href="?page={{ posts_queryset.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ posts_queryset.number }} of {{ posts_queryset.paginator.num_pages }}.
                </span>

                {% if posts_queryset.has_next %}
                <a href="?page={{ posts_queryset.next_page_number }}">next</a>
                {% endif %}
            </span>
            </div>
            {% endif %}
        </div>

    </div>
</div>
{% endblock content %}

posts/templates/posts/events.html
{% extends 'disclifts/base.html' %}
{% load staticfiles%}


{% block title %}Events ¦{% endblock title %}

{% block content%}
<div class="container">
    <h2>Upcoming events</h2>
    <h4>Select an event to see all posts</h4>
    <div class="row">
        <div class="col-sm-10">
            {% include 'posts/events_table.html' %}
        </div> <!--col-->
        <div class="col-sm-2">
            <p><a class="btn btn-primary btn-lg" href="{% url 'posts:add_event' %}" role="button">Create new event</a>
            </p>
            <p><a class="btn btn-primary btn-lg" href="{% url 'posts:past_events' %}" role="button">View past events</a>
            </p>
        </div> <!--col-->
    </div> <!--row-->
    <div class="pagination">
    <span class="step-links">
        {% if events_queryset.has_previous %}
        <a href="?page={{ events_queryset.previous_page_number }}">previous</a>
        {% endif %}
        <span class="current">
            Page {{ events_queryset.number }} of {{ events_queryset.paginator.num_pages }}.
        </span>
        {% if events_queryset.has_next %}
        <a href="?page={{ events_queryset.next_page_number }}">next</a>
        {% endif %}
    </span>
    </div>
</div>
{% endblock content %}

posts/templates/posts/events_table.html
<table class="table table-hover">
    <thead>
    <tr>
        <th>Event</th>
        <th>Location</th>
        <th>Date</th>
        <th>Posts</th>
    </tr>
    </thead>
    <tbody>
    {% for instance in events_queryset %}
    <tr class="clickable-row" data-url="{{ instance.get_absolute_url }}">
        <td>{{instance.title}}</td>
        <td>{{instance.location}}</td>
        {% if instance.start_date|date:"m" == instance.end_date|date:"m" %}
        <td>{{instance.start_date|date:"d"}}-{{instance.end_date|date:"d M Y"}}</td>
        {% else %}
        <td>{{instance.start_date|date:"d M"}} - {{instance.end_date|date:"d M Y"}}</td>
        {% endif %}
        <td>{{instance.posts_set.all.count}}</td>
        {# This gets all the posts with a foreign key relationship to model instance #}
        {# of the event, and counts #}
        {# how many there are. Note the p in .posts_set is lower case #}
    </tr>
    {% endfor %}
    </tbody>
</table>

posts/templates/posts/how_it_works.html
{% extends 'disclifts/base.html' %}

{% block title %}How it works ¦{% endblock title %}

{% block content %}
<div class="container container-reduced-top-padding">
    <h2>
        How it all works
    </h2>
    <div class="row">
        <div class="col-sm-12">
            <div class="explanation-box">
                <h3>
                    Got some extra space in your car?
                </h3>
                <div class="explanation">
                    <dl>
                        <dt>Find the event you are driving to on the <a href="{% url 'posts:events' %}">Events page</a>
                            or
                            the
                            homepage will always show the next 5
                            events.
                        </dt>
                        <dt>Press the
                            <button class="btn btn-primary btn-lg btn-demo" role="button">Create new
                                post
                            </button>
                            and create a new post with details about when and where you are leaving from.
                        </dt>
                        <dt>Sit back and relax, you will recieve an email notification when someone responds to your
                            post.
                        </dt>
                        <dt>Opt - Be proactive, browse the event for 'I need a ride' posts and message them to help them
                            out.
                        </dt>
                    </dl>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12" id="need-lift-explanation">
            <div class="explanation-box">
                <h3>
                    Need a lift?
                </h3>
                <dl class="explanation">
                    <dt>Find the event you are going to on the <a href="{% url 'posts:events' %}">Events page</a> or the
                        homepage
                        will always show the next 5
                        events.
                    </dt>
                    <dt>Press the
                        <button class="btn btn-primary btn-lg btn-demo" role="button">Create new
                            post
                        </button>
                        and create a new post with details about needing a ride.
                    </dt>
                    <dt>Browse the event for posts that show they have space.</dt>
                    <dt>If you find a post simply click on it for further details and message the user with the
                        <button class="btn btn-primary btn-demo">
                            Message user
                        </button>
                        which will take you to a write a message page.
                    </dt>
                </dl>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="explanation-box no-event">
                <h3>
                    Can't find an event?
                </h3>
                <dl>
                    <dt>You can create a new event easily with the create new event form found <a
                            href="{% url 'posts:add_event' %}">here</a>.
                    </dt>
                </dl>

            </div>
        </div>
    </div>
</div>
{% endblock content %}

posts/templates/posts/index.html
{% extends 'disclifts/base.html' %}
{% load staticfiles %}


{% block title %}Home ¦{% endblock title %}
{% block content%}
<div class="container-reduced-top-padding">
    <img id="banner-img" class="" src="{% static 'img/dl_banner.png' %}">
    {% if not request.user.is_authenticated %}

    <div class="signup-banner box box5 shadow5">
        <h3 class="compact">
            <strong>Help frisbee tournaments get greener.</strong>
            Meet frisbee folk and sharing rides.
            <span class="action-btns">
            <a class="btn btn-lg btn-primary" href="/accounts/signup/" role="button">Signup!</a>
            <a class="btn btn-lg btn-primary" href="{% url 'posts:how_it_works' %}" role="button">Learn more</a>
        </span>
        </h3>

    </div>


    <!--<div class="jumbotron" id="jumbotron-signup">-->
        <!--&lt;!&ndash;<h2>Disc Lifts</h2>&ndash;&gt;-->
        <!--<p>The site that helps you find or offer car pooling for frisbee tournaments. Help make the world go a little-->
            <!--greener, share a ride.</p>-->
        <!--<p></p>-->
        <!--<p>-->
            <!--<a class="btn btn-lg btn-primary" href="/accounts/signup/" role="button">Signup! &raquo;</a>-->
            <!--<a class="btn btn-lg btn-primary" href="{% url 'posts:how_it_works' %}" role="button">How it-->
                <!--works &raquo;</a>-->
        <!--</p>-->
    <!--</div>-->
    {% endif %}


    <div class="row">
        <div class="col-sm-8">
            <p>
            <h2>Upcoming events</h2>
            <h4>Select an event to see all posts - <a href="{% url 'posts:events' %}">or view all events here.</a></h4>
            </p>
            {% include 'posts/events_table.html' %}
        </div>


        <div class="col-sm-4">
            <div class="jumbotron jumbotron-get-involved" style="background-color: white   ">
                <h2>Get involved</h2>
                <p><a class="btn btn-primary btn-lg" href="{% url 'posts:add_event' %}" role="button">Create new
                    event &raquo;</a></p>
                <p><a class="btn btn-primary btn-lg" href="{% url 'posts:add_post' %}" role="button">Create new
                    post &raquo;</a>
                </p>
                {% if request.user.is_authenticated %}
                <p><a class="btn btn-primary btn-lg" href="{% url 'posts:how_it_works' %}" role="button">How it
                    works &raquo;</a></p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

posts/templates/posts/index2.html
{% extends 'disclifts/base.html' %}
{% load staticfiles %}


{% block title %}Home ¦{% endblock title %}
{% block content%}
<div class="container-reduced-top-padding">
    <img id="banner-img" class="" src="static/img/dl_banner.png">
    {% if not request.user.is_authenticated %}

    <div class="jumbotron" id="jumbotron-signup">
        <!--<h2>Disc Lifts</h2>-->
        <p>The site that helps you find or offer car pooling for frisbee tournaments. Help make the world go a little
            greener, share a ride.</p>
        <p></p>
        <p>
            <a class="btn btn-lg btn-primary" href="/accounts/signup/" role="button">Signup! &raquo;</a>
            <a class="btn btn-lg btn-primary" href="{% url 'posts:how_it_works' %}" role="button">How it
                works &raquo;</a>
        </p>
    </div>
    {% endif %}


    <div class="row">
        <div class="col-sm-8">
            <p>
            <h2>Upcoming events</h2>
            <h4>Select an event to see all posts - <a href="{% url 'posts:events' %}">or view all events here.</a></h4>
            </p>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Event</th>
                    <th>Location</th>
                    <th>Date</th>
                    <th>Posts</th>
                </tr>
                </thead>
                <tbody>
                {% for instance in queryset %}
                <tr class="clickable-row" data-url="{{ instance.get_absolute_url }}">
                    <td>{{instance.title}}</td>
                    <td>{{instance.location}}</td>
                    {% if instance.start_date|date:"m" == instance.end_date|date:"m" %}
                    <td>{{instance.start_date|date:"d"}}-{{instance.end_date|date:"d M Y"}}</td>
                    {% else %}
                    <td>{{instance.start_date|date:"d M"}} - {{instance.end_date|date:"d M Y"}}</td>
                    {% endif %}
                    <td>{{instance.posts_set.all.count}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


        <div class="col-sm-4">
            <div class="jumbotron" style="background-color: white   ">
                <h2 id="jumbotron-title-homepage">Get involved</h2>
                <p><a class="btn btn-primary btn-lg" href="{% url 'posts:add_event' %}" role="button">Create new
                    event &raquo;</a></p>
                <p><a class="btn btn-primary btn-lg" href="{% url 'posts:add_post' %}" role="button">Create new
                    post &raquo;</a>
                </p>
                {% if request.user.is_authenticated %}
                <p><a class="btn btn-primary btn-lg" href="{% url 'posts:how_it_works' %}" role="button">How it
                    works &raquo;</a></p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

posts/templates/posts/posts.html
{% extends 'disclifts/base.html' %}

{% block title %}Post ¦{% endblock title %}

{% block content %}
<div class="container">
    <h2>
        <a class="posts_header" href="{% url 'posts:event_posts' id=posts_instance.event_id %}">{{posts_instance.event}}
        </a>
        - Posted by <a class="posts_header" href="{% url 'user:profile' posts_instance.user_id %}">{{posts_instance.user}}</a>
    </h2>
    <div class="row">
        <div class="col-sm-12">


            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Lift Type</th>
                    <th>Location</th>
                    <th>Leaving Date</th>
                    <th>Leaving time</th>
                    <th>Return Date</th>
                    <th>Spaces</th>
                    <th>Fulfilled</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{% if posts_instance.lift_type == 'I have space' %}
                        <i class="fa fa-car" aria-hidden="true"></i> I have space
                        {% else %}
                        <i class="fa fa-thumbs-up" aria-hidden="true"></i> I need a ride
                        {%endif%}
                    </td>
                    <td>{{posts_instance.location}}</td>
                    <td>{{posts_instance.leaving_date}}</td>
                    <td>{{ posts_instance.leaving_time }}</td>
                    <td>{{ posts_instance.return_date }}</td>
                    <td>{{posts_instance.spaces}}</td>
                    <td><input type="checkbox" name="fulfilled" {% if posts_instance.fulfilled %}checked=""
                               {%else%}{%endif%}
                               disabled="true">
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            {% if posts_instance.comments != ""%}
            <h3>Comments</h3>
            <p class="posts_comments">{{posts_instance.comments}}</p>
            {% endif %}
        </div>
        <div class="col-sm-6">
            {% if current_user_id == posts_instance.user_id %}
            <a role="button" class="btn btn-primary" href="{% url 'posts:edit_post' posts_instance.id %}">
                Edit post
            </a>
            <a role="button" class="btn btn-danger" href="{% url 'posts:delete_post' posts_instance.id %}"
               onclick="return confirm('Are you sure you want to delete your post?');">
                Delete post
            </a>
            {% else %}
            <a role="button" class="btn btn-primary" href="{% url 'postman:write' posts_instance.user %}?subject={{posts_instance.event}}">
                Message {{posts_instance.user }}
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}